version: '3'
services:
  postgresPocessEngine:
    image: "postgres:10.6"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "processengine"

